os: Visual Studio 2017
image: Visual Studio 2017

environment:
  AppVeyor: APPVEYOR

configuration: 
- Release

before_build:
  - cmd: nuget update -self
  - nuget restore

build:
  parallel: true
  project: CQL.sln

artifacts:
  - path: CQL/bin/%CONFIGURATION%/*/CQL.*
  - path: CQL/bin/%CONFIGURATION%/*.nupkg
